/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function encodeSync(src: Uint8Array, dest: Uint8Array): Uint8Array
export declare function decodeSync(src: Uint8Array, patch: Uint8Array): Uint8Array
